//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DynamicBridge.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DynamicBridge.Resources.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 1. 命名层组设计： 的本地化字符串。
        /// </summary>
        public static string _1NameLayeredDesign {
            get {
                return ResourceManager.GetString("_1NameLayeredDesign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 2. 选择Glamourer设计: 的本地化字符串。
        /// </summary>
        public static string _2SelectGlamourerDesigns {
            get {
                return ResourceManager.GetString("_2SelectGlamourerDesigns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 3. 更改顺序（如果需要） 的本地化字符串。
        /// </summary>
        public static string _3ChangeOrderIfNeeded {
            get {
                return ResourceManager.GetString("_3ChangeOrderIfNeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关于 的本地化字符串。
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加新条目 的本地化字符串。
        /// </summary>
        public static string AddNewEntry {
            get {
                return ResourceManager.GetString("AddNewEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加预设组 的本地化字符串。
        /// </summary>
        public static string AddNewPresetFolder {
            get {
                return ResourceManager.GetString("AddNewPresetFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加新规则 的本地化字符串。
        /// </summary>
        public static string AddNewRule {
            get {
                return ResourceManager.GetString("AddNewRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 允许选择为其他角色添加的称号 的本地化字符串。
        /// </summary>
        public static string AllowSelectingTitlesRegisteredForOtherCharacters {
            get {
                return ResourceManager.GetString("AllowSelectingTitlesRegisteredForOtherCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ...并删除包含的预设（按住CTRL+SHIFT） 的本地化字符串。
        /// </summary>
        public static string AndDeleteIncludedProfilesHoldCTRLSHIFT {
            get {
                return ResourceManager.GetString("AndDeleteIncludedProfilesHoldCTRLSHIFT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  and $ more 的本地化字符串。
        /// </summary>
        public static string AndMore {
            get {
                return ResourceManager.GetString("AndMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ...并将包含的预设移动到默认组（按住CTRL） 的本地化字符串。
        /// </summary>
        public static string AndMoveProfilesToDefaultFolderHoldCTRL {
            get {
                return ResourceManager.GetString("AndMoveProfilesToDefaultFolderHoldCTRL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 分配的配置文件 的本地化字符串。
        /// </summary>
        public static string AssignedProfile {
            get {
                return ResourceManager.GetString("AssignedProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 分配类型： 的本地化字符串。
        /// </summary>
        public static string AssignmentType {
            get {
                return ResourceManager.GetString("AssignmentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择后，自动使用第一个选定插件的选项名称填充空预设名称 的本地化字符串。
        /// </summary>
        public static string AutofillEmptyNames {
            get {
                return ResourceManager.GetString("AutofillEmptyNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 为 $ 自动生成的配置文件 的本地化字符串。
        /// </summary>
        public static string AutogeneratedProfileFor {
            get {
                return ResourceManager.GetString("AutogeneratedProfileFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您【必须】启用此设置或禁用Glamourer的自动执行，否则Glamourer或DynamicBridge的动态规则将无法正常工作。 的本地化字符串。
        /// </summary>
        public static string AutomationWarning {
            get {
                return ResourceManager.GetString("AutomationWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 基础预设 的本地化字符串。
        /// </summary>
        public static string BasePreset {
            get {
                return ResourceManager.GetString("BasePreset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 将$1. 加入和名单。这将阻止它出现在配置文件分配中。这也将撤消$1. 的配置文件分配。 的本地化字符串。
        /// </summary>
        public static string BlacklistCharaTooltip {
            get {
                return ResourceManager.GetString("BlacklistCharaTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &quot;$&quot; 已被列入黑名单。选择另一个配置文件进行编辑。 的本地化字符串。
        /// </summary>
        public static string BlacklistedCharacter {
            get {
                return ResourceManager.GetString("BlacklistedCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 按下此按钮后，隐匿的名称将发生更改。 的本地化字符串。
        /// </summary>
        public static string CensorHelp {
            get {
                return ResourceManager.GetString("CensorHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 角色已列入黑名单 的本地化字符串。
        /// </summary>
        public static string CharacterBlacklisted {
            get {
                return ResourceManager.GetString("CharacterBlacklisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &quot;$&quot; 没有关联的配置文件。选择其他配置文件进行编辑或在“角色管理”选项卡中进行关联。 的本地化字符串。
        /// </summary>
        public static string CharaNoAssociation {
            get {
                return ResourceManager.GetString("CharaNoAssociation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [DynamicBridge] Glamourer自动执行已启用，但是DynamicBridge还未配置为与其协同运行。 这将导致问题。请禁用Glamourer自动执行或在DynamicBridge插件设置选项卡中进行设置（使用命令/db或/db - settings打开设置窗口）。 的本地化字符串。
        /// </summary>
        public static string ChatNoticeGlamourerWarning {
            get {
                return ResourceManager.GetString("ChatNoticeGlamourerWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开插件设置窗口\n/db apply - 立即重新应用规则\n/db static &lt;name&gt; - 将预设标记为静态\n/db dynamic - 取消静态预设，使用动态规则 的本地化字符串。
        /// </summary>
        public static string CommangHelp {
            get {
                return ResourceManager.GetString("CommangHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 在此处，您可以创建一个基于Glamourer模板的叠加组合设计。一旦生效，它们将按顺序被依次应用（比如在Glamourer里第一个模板规则是仅应用外貌，第二个模板仅应用装备，他们将组合起来），越靠下优先级越高。在规则里，可以同时选择层组设计和Glamourer模板。 的本地化字符串。
        /// </summary>
        public static string ComplexGlamourerHelp {
            get {
                return ResourceManager.GetString("ComplexGlamourerHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 配置规则条件 的本地化字符串。
        /// </summary>
        public static string ConfigureRuleConditions {
            get {
                return ResourceManager.GetString("ConfigureRuleConditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 （副本） 的本地化字符串。
        /// </summary>
        public static string CopySuffix {
            get {
                return ResourceManager.GetString("CopySuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  (副本 $) 的本地化字符串。
        /// </summary>
        public static string CopySuffixWithNumber {
            get {
                return ResourceManager.GetString("CopySuffixWithNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 将此配置文件复制到剪贴板 的本地化字符串。
        /// </summary>
        public static string CopyThisProfileToClipboard {
            get {
                return ResourceManager.GetString("CopyThisProfileToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 复制到剪贴板 的本地化字符串。
        /// </summary>
        public static string CopyToClipboard {
            get {
                return ResourceManager.GetString("CopyToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无法从剪贴板导入 的本地化字符串。
        /// </summary>
        public static string CouldNotImportFromClipboard {
            get {
                return ResourceManager.GetString("CouldNotImportFromClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 创建空白配置 的本地化字符串。
        /// </summary>
        public static string CreateEmpty {
            get {
                return ResourceManager.GetString("CreateEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 创建新的空白的配置文件 的本地化字符串。
        /// </summary>
        public static string CreateNewEmptyProfile {
            get {
                return ResourceManager.GetString("CreateNewEmptyProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 创建新的空白配置文件并将其分配给当前角色 的本地化字符串。
        /// </summary>
        public static string CreateNewEmptyProfileAndAssignItToCurrentCharacter {
            get {
                return ResourceManager.GetString("CreateNewEmptyProfileAndAssignItToCurrentCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 - 当前角色 - 的本地化字符串。
        /// </summary>
        public static string CurrentCharacterSelectable {
            get {
                return ResourceManager.GetString("CurrentCharacterSelectable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前：$1/$2 的本地化字符串。
        /// </summary>
        public static string CurrentEmote {
            get {
                return ResourceManager.GetString("CurrentEmote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 所有在C+中添加的[角色配置]都会显示在全局预设中，但只会使用指定给当前角色的配置。 的本地化字符串。
        /// </summary>
        public static string CustomizePlusGlobalNotice {
            get {
                return ResourceManager.GetString("CustomizePlusGlobalNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除 的本地化字符串。
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除组... 的本地化字符串。
        /// </summary>
        public static string DeleteFolder {
            get {
                return ResourceManager.GetString("DeleteFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 按住CTRL键并单击可删除有关$1. 的信息。这也将撤消对该角色的配置文件分配，但一旦您重新登记该角色，$1. 将再次在插件中注册。 的本地化字符串。
        /// </summary>
        public static string DeleteTooltip {
            get {
                return ResourceManager.GetString("DeleteTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 如果启用此选项，你可以使用×标记任何条件。如果一条动态规则中匹配到任何×标的条件，则忽略整条规则。 的本地化字符串。
        /// </summary>
        public static string DenyCondHelp {
            get {
                return ResourceManager.GetString("DenyCondHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 如果匹配到任何被打×的条件，规则不会被应用。 的本地化字符串。
        /// </summary>
        public static string DenyConditionsTooltip {
            get {
                return ResourceManager.GetString("DenyConditionsTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 允许使用否定条件 的本地化字符串。
        /// </summary>
        public static string Draw_AllowApplyingNegativeConditions {
            get {
                return ResourceManager.GetString("Draw_AllowApplyingNegativeConditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下拉菜单尺寸 的本地化字符串。
        /// </summary>
        public static string Draw_DropdownMenuSize {
            get {
                return ResourceManager.GetString("Draw_DropdownMenuSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启用插件 的本地化字符串。
        /// </summary>
        public static string Draw_EnablePlugin {
            get {
                return ResourceManager.GetString("Draw_EnablePlugin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 常规 的本地化字符串。
        /// </summary>
        public static string Draw_General {
            get {
                return ResourceManager.GetString("Draw_General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 隐藏教程 的本地化字符串。
        /// </summary>
        public static string Draw_HideTutorial {
            get {
                return ResourceManager.GetString("Draw_HideTutorial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未找到Glamourer规则时，DynamicBridge的行为： 的本地化字符串。
        /// </summary>
        public static string DynamicBridgeBehaviorWhenNoGlamourerRuleIsFound {
            get {
                return ResourceManager.GetString("DynamicBridgeBehaviorWhenNoGlamourerRuleIsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启用此规则 的本地化字符串。
        /// </summary>
        public static string EnableThisRule {
            get {
                return ResourceManager.GetString("EnableThisRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 名称不能为空值 的本地化字符串。
        /// </summary>
        public static string ErrorNameCanNotBeEmpty {
            get {
                return ResourceManager.GetString("ErrorNameCanNotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 名称必须是唯一值 的本地化字符串。
        /// </summary>
        public static string ErrorNameMustBeUnique {
            get {
                return ResourceManager.GetString("ErrorNameMustBeUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导出到剪贴板 的本地化字符串。
        /// </summary>
        public static string ExportToClipboard {
            get {
                return ResourceManager.GetString("ExportToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 在动态规则里启用或禁用条件选项，以优化使用体验并提高性能。 的本地化字符串。
        /// </summary>
        public static string ExtraHelp {
            get {
                return ResourceManager.GetString("ExtraHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无法从剪贴板粘贴：\n 的本地化字符串。
        /// </summary>
        public static string FailedToPasteFromClipboardN {
            get {
                return ResourceManager.GetString("FailedToPasteFromClipboardN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 此预设值将用作当前配置文件中的默认值。 的本地化字符串。
        /// </summary>
        public static string FallbackNotice {
            get {
                return ResourceManager.GetString("FallbackNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 备用预设 的本地化字符串。
        /// </summary>
        public static string FallbackPresetSection {
            get {
                return ResourceManager.GetString("FallbackPresetSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 筛选... 的本地化字符串。
        /// </summary>
        public static string Filter {
            get {
                return ResourceManager.GetString("Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 组名称 的本地化字符串。
        /// </summary>
        public static string FolderName {
            get {
                return ResourceManager.GetString("FolderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 折叠组白名单 的本地化字符串。
        /// </summary>
        public static string FolderWhitelistColumn {
            get {
                return ResourceManager.GetString("FolderWhitelistColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 在职业或套装改变时强制更新外观。 的本地化字符串。
        /// </summary>
        public static string ForceUpdateSetting {
            get {
                return ResourceManager.GetString("ForceUpdateSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 强制更新角色，重新应用所有规则并重置 的本地化字符串。
        /// </summary>
        public static string ForceUpdateYourCharacterReapplyingAllRulesAndResets {
            get {
                return ResourceManager.GetString("ForceUpdateYourCharacterReapplyingAllRulesAndResets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 在预设编辑器中显示Glamourer角色设计的完整路径（如果有）。 的本地化字符串。
        /// </summary>
        public static string FullPath {
            get {
                return ResourceManager.GetString("FullPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 $ 未找到名称 的本地化字符串。
        /// </summary>
        public static string GearsetFallbackName {
            get {
                return ResourceManager.GetString("GearsetFallbackName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Glamourer在插件设置中被禁用。功能不可用。 的本地化字符串。
        /// </summary>
        public static string GlamourerDisabledInSettingsFunctionUnavailable {
            get {
                return ResourceManager.GetString("GlamourerDisabledInSettingsFunctionUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 全局预设可用于您的每个角色。 的本地化字符串。
        /// </summary>
        public static string GlobalPresetsNote {
            get {
                return ResourceManager.GetString("GlobalPresetsNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [Beta] 恢复到应用规则前的外观 的本地化字符串。
        /// </summary>
        public static string GuiSettings_BetaRestoreAppearanceAsItWasBeforeApplyingRule {
            get {
                return ResourceManager.GetString("GuiSettings_BetaRestoreAppearanceAsItWasBeforeApplyingRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 大 的本地化字符串。
        /// </summary>
        public static string GuiSettings_Large {
            get {
                return ResourceManager.GetString("GuiSettings_Large", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 尽可能最大 的本地化字符串。
        /// </summary>
        public static string GuiSettings_MaximumPossible {
            get {
                return ResourceManager.GetString("GuiSettings_MaximumPossible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 恢复到游戏状态 的本地化字符串。
        /// </summary>
        public static string GuiSettings_RevertToGameState {
            get {
                return ResourceManager.GetString("GuiSettings_RevertToGameState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 恢复到Glamourer的自动执行 的本地化字符串。
        /// </summary>
        public static string GuiSettings_RevertToGlamourerSAutomation {
            get {
                return ResourceManager.GetString("GuiSettings_RevertToGlamourerSAutomation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 小 的本地化字符串。
        /// </summary>
        public static string GuiSettings_Small {
            get {
                return ResourceManager.GetString("GuiSettings_Small", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 标准 的本地化字符串。
        /// </summary>
        public static string GuiSettings_Standard {
            get {
                return ResourceManager.GetString("GuiSettings_Standard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 在动态规则中被隐藏 的本地化字符串。
        /// </summary>
        public static string HiddenFromRules {
            get {
                return ResourceManager.GetString("HiddenFromRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 在动态规则的预设下拉菜单中隐藏 的本地化字符串。
        /// </summary>
        public static string HideFromRulesSection {
            get {
                return ResourceManager.GetString("HideFromRulesSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 按住CTRL并点击来删除 的本地化字符串。
        /// </summary>
        public static string HoldCTRLAndClickToDelete {
            get {
                return ResourceManager.GetString("HoldCTRLAndClickToDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 按住CTRL+点击来删除 的本地化字符串。
        /// </summary>
        public static string HoldCTRLClickToDelete {
            get {
                return ResourceManager.GetString("HoldCTRLClickToDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 按住CTRL键并点击来取消分配配置文件 $1 给 $2. 的本地化字符串。
        /// </summary>
        public static string HoldCTRLKeyAndClickToUnassignProfile1From2 {
            get {
                return ResourceManager.GetString("HoldCTRLKeyAndClickToUnassignProfile1From2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 所有在Honorific中添加的称号都会显示在全局预设中，但只会使用指定给当前角色的配置。\n除非在设置中启用了“允许选择为其他角色添加的称号”。 的本地化字符串。
        /// </summary>
        public static string HonorificGlobalPresetNotice {
            get {
                return ResourceManager.GetString("HonorificGlobalPresetNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前住宅：$ 的本地化字符串。
        /// </summary>
        public static string HouseReg_Draw_CurrentHouse {
            get {
                return ResourceManager.GetString("HouseReg_Draw_CurrentHouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 登记此住宅 的本地化字符串。
        /// </summary>
        public static string HouseReg_Draw_RegisterThisHouse {
            get {
                return ResourceManager.GetString("HouseReg_Draw_RegisterThisHouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您未处于住宅中 的本地化字符串。
        /// </summary>
        public static string HouseReg_Draw_YouAreNotInHouse {
            get {
                return ResourceManager.GetString("HouseReg_Draw_YouAreNotInHouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 在此处，您可以登记住宅。登记后可以在“动态规则”选项卡中选择它作为条件。 的本地化字符串。
        /// </summary>
        public static string HouseRegHelp {
            get {
                return ResourceManager.GetString("HouseRegHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ID 的本地化字符串。
        /// </summary>
        public static string IDColumn {
            get {
                return ResourceManager.GetString("IDColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重新生成匿名种子 的本地化字符串。
        /// </summary>
        public static string IncognitoCensor {
            get {
                return ResourceManager.GetString("IncognitoCensor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [Beta] 启用匿名模式（正在开发，仅在某些位置匿名） 的本地化字符串。
        /// </summary>
        public static string IncognitoEnable {
            get {
                return ResourceManager.GetString("IncognitoEnable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 将角色名称替换为随机动物名称，将服务器名称替换为任意幻想世界名称。相同的对象总是会产生相同的名字，对你来说是这样，但对其他人来说却不是。此外，隐藏输入字段中的文本，并显示临时配置文件/预设ID来代替。 的本地化字符串。
        /// </summary>
        public static string IncognitoHelp {
            get {
                return ResourceManager.GetString("IncognitoHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 尽可能只使用首字母替换原文字。 的本地化字符串。
        /// </summary>
        public static string IncognitoReplacement {
            get {
                return ResourceManager.GetString("IncognitoReplacement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 警告！在日志和调试选项卡以及卫月日志中仍会显示真实名称！\n警告！如果要分享配置文件并且启用了匿名，拿到文件的人[可以恢复真实名称]。如果你需要向他人发送配置文件并保持匿名状态，请单击“重新生成匿名种子”按钮，发送配置文件，并再次单击该按钮。 的本地化字符串。
        /// </summary>
        public static string IncognitoWarning {
            get {
                return ResourceManager.GetString("IncognitoWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 集成 的本地化字符串。
        /// </summary>
        public static string Integrations {
            get {
                return ResourceManager.GetString("Integrations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 在此处，您可以单独启用/禁用插件集成，并配置相关设置。 的本地化字符串。
        /// </summary>
        public static string IntegrationsHelp {
            get {
                return ResourceManager.GetString("IntegrationsHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 它没有被 &quot;$&quot; 使用。 的本地化字符串。
        /// </summary>
        public static string ItIsNotUsedBy {
            get {
                return ResourceManager.GetString("ItIsNotUsedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 加入Discord获取支持和更新日志 的本地化字符串。
        /// </summary>
        public static string JoinDiscordForSupportAndChangelogs {
            get {
                return ResourceManager.GetString("JoinDiscordForSupportAndChangelogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 层组设计 的本地化字符串。
        /// </summary>
        public static string LayeredDesigns {
            get {
                return ResourceManager.GetString("LayeredDesigns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 由于插件版本已变更，已创建当前配置的备份。 的本地化字符串。
        /// </summary>
        public static string LogNoticeVersionChange {
            get {
                return ResourceManager.GetString("LogNoticeVersionChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 由 NightmareXIV 与 AsunaTsuki 联合制作 的本地化字符串。
        /// </summary>
        public static string MadeByNightmareXIVInCollaborationWithAsunaTsuki {
            get {
                return ResourceManager.GetString("MadeByNightmareXIVInCollaborationWithAsunaTsuki", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 主预设组 的本地化字符串。
        /// </summary>
        public static string MainPresetsFolder {
            get {
                return ResourceManager.GetString("MainPresetsFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 满足以下任何条件都将触发规则：\n 的本地化字符串。
        /// </summary>
        public static string MeetingAnyOfTheFollowingConditionsWillResultInRuleBeingTriggeredN {
            get {
                return ResourceManager.GetString("MeetingAnyOfTheFollowingConditionsWillResultInRuleBeingTriggeredN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 满足以下任何条件都将使规则无效： 的本地化字符串。
        /// </summary>
        public static string MeetingAnyOfTheseConditionWillMakeRuleInvalid {
            get {
                return ResourceManager.GetString("MeetingAnyOfTheseConditionWillMakeRuleInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 状态预设 的本地化字符串。
        /// </summary>
        public static string MoodlePresets {
            get {
                return ResourceManager.GetString("MoodlePresets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 所有选择的Moodles/预设都将被应用：\n$ 的本地化字符串。
        /// </summary>
        public static string MoodlesApplicationTooltip {
            get {
                return ResourceManager.GetString("MoodlesApplicationTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 在此预设被取消应用的同时取消此附加状态。 的本地化字符串。
        /// </summary>
        public static string MoodlesCancelTooltip {
            get {
                return ResourceManager.GetString("MoodlesCancelTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下移 的本地化字符串。
        /// </summary>
        public static string MoveDown {
            get {
                return ResourceManager.GetString("MoveDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 - 默认组 - 的本地化字符串。
        /// </summary>
        public static string MoveToMainFolder {
            get {
                return ResourceManager.GetString("MoveToMainFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上移 的本地化字符串。
        /// </summary>
        public static string MoveUp {
            get {
                return ResourceManager.GetString("MoveUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 名称 的本地化字符串。
        /// </summary>
        public static string NameColumn {
            get {
                return ResourceManager.GetString("NameColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新建配置 $ 的本地化字符串。
        /// </summary>
        public static string NewProfileName {
            get {
                return ResourceManager.GetString("NewProfileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 使用剪贴板中的数据创建新配置文件 的本地化字符串。
        /// </summary>
        public static string NewProfilePasteTooltip {
            get {
                return ResourceManager.GetString("NewProfilePasteTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 没有关联的配置文件 的本地化字符串。
        /// </summary>
        public static string NoAssociatedProfile {
            get {
                return ResourceManager.GetString("NoAssociatedProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 - 未选择 - 的本地化字符串。
        /// </summary>
        public static string NoneSelection {
            get {
                return ResourceManager.GetString("NoneSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 - 不分配 - 的本地化字符串。
        /// </summary>
        public static string NoProfileSelectable {
            get {
                return ResourceManager.GetString("NoProfileSelectable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 角色已被列入黑名单或未登录。 的本地化字符串。
        /// </summary>
        public static string NoticeCharacterBlacklistedOrNotLoggedIn {
            get {
                return ResourceManager.GetString("NoticeCharacterBlacklistedOrNotLoggedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无法找到预设 $. 的本地化字符串。
        /// </summary>
        public static string NoticeNotFound {
            get {
                return ResourceManager.GetString("NoticeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 $ 已设为静态。 的本地化字符串。
        /// </summary>
        public static string NotifyWasMadeStatic {
            get {
                return ResourceManager.GetString("NotifyWasMadeStatic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未安装 的本地化字符串。
        /// </summary>
        public static string NotInstalled {
            get {
                return ResourceManager.GetString("NotInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 $1 | $2 已选中 的本地化字符串。
        /// </summary>
        public static string NotListSelected {
            get {
                return ResourceManager.GetString("NotListSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未登录 的本地化字符串。
        /// </summary>
        public static string NotLoggedIn {
            get {
                return ResourceManager.GetString("NotLoggedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 仅显示已选择项 的本地化字符串。
        /// </summary>
        public static string OnlySelected {
            get {
                return ResourceManager.GetString("OnlySelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开白名单编辑器 的本地化字符串。
        /// </summary>
        public static string OpenAllowListEditor {
            get {
                return ResourceManager.GetString("OpenAllowListEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开黑名单编辑器 的本地化字符串。
        /// </summary>
        public static string OpenDenyListEditor {
            get {
                return ResourceManager.GetString("OpenDenyListEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选中后忽略此规则。DynamicBridge在遍历规则时会跳过此规则继续搜索，所有规则将依次应用。 的本地化字符串。
        /// </summary>
        public static string PassthroughTooltip {
            get {
                return ResourceManager.GetString("PassthroughTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 从剪贴板粘贴 的本地化字符串。
        /// </summary>
        public static string PasteFromClipboard {
            get {
                return ResourceManager.GetString("PasteFromClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 从剪贴板粘贴以前复制的预设 的本地化字符串。
        /// </summary>
        public static string PastePreviouslyCopiedPresetFromClipboard {
            get {
                return ResourceManager.GetString("PastePreviouslyCopiedPresetFromClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 从剪切板粘贴规则 的本地化字符串。
        /// </summary>
        public static string PasteRuleFromClipboard {
            get {
                return ResourceManager.GetString("PasteRuleFromClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 插件已被设置禁用 的本地化字符串。
        /// </summary>
        public static string PLUGINDISABLEDBYSETTINGS {
            get {
                return ResourceManager.GetString("PLUGINDISABLEDBYSETTINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 预设 $ 已被设置为静态。动态规则自动执行已禁用。 的本地化字符串。
        /// </summary>
        public static string PresetIsSelectedAsStaticAutomationDisabled {
            get {
                return ResourceManager.GetString("PresetIsSelectedAsStaticAutomationDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 预设名称 的本地化字符串。
        /// </summary>
        public static string PresetName {
            get {
                return ResourceManager.GetString("PresetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加空预设到默认组或焦点组 的本地化字符串。
        /// </summary>
        public static string Presets_AddNewEmpty {
            get {
                return ResourceManager.GetString("Presets.AddNewEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 预设组 $ 的本地化字符串。
        /// </summary>
        public static string Presets_PresetFolder {
            get {
                return ResourceManager.GetString("Presets_PresetFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 将此预设设置为静态：此预设会无视任何规则，无条件地应用于此角色。 的本地化字符串。
        /// </summary>
        public static string PresetStaticSetNotice {
            get {
                return ResourceManager.GetString("PresetStaticSetNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 配置文件 $ 的本地化字符串。
        /// </summary>
        public static string ProfileTitle {
            get {
                return ResourceManager.GetString("ProfileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 阅读说明和常见问题解答 的本地化字符串。
        /// </summary>
        public static string ReadInstructionsAndFAQ {
            get {
                return ResourceManager.GetString("ReadInstructionsAndFAQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 允许DynamicBridge管理Glamourer的自动执行设置。 的本地化字符串。
        /// </summary>
        public static string ReflectAutomation {
            get {
                return ResourceManager.GetString("ReflectAutomation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 如果启用此设置，Glamourer的全局自动执行将在应用任何规则时自动禁用，并在找不到规则时自动启用。 的本地化字符串。
        /// </summary>
        public static string ReflectAutomationHelp {
            get {
                return ResourceManager.GetString("ReflectAutomationHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 在GitHub上报告问题、请求功能或提问 的本地化字符串。
        /// </summary>
        public static string ReportIssueRequestFeatureOrAskAQuestionOnGitHub {
            get {
                return ResourceManager.GetString("ReportIssueRequestFeatureOrAskAQuestionOnGitHub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 在应用规则前还原角色 的本地化字符串。
        /// </summary>
        public static string RevertCharacterBeforeApplyingRule {
            get {
                return ResourceManager.GetString("RevertCharacterBeforeApplyingRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 在恢复自动执行前还原角色 的本地化字符串。
        /// </summary>
        public static string RevertCharacterBeforeRestoringAutomation {
            get {
                return ResourceManager.GetString("RevertCharacterBeforeRestoringAutomation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 如果您正在使用Glamourer的自动执行，建议选择“恢复到Glamourer的自动执行”。 的本地化字符串。
        /// </summary>
        public static string RevertTooltip {
            get {
                return ResourceManager.GetString("RevertTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 鼠标右键点击打开上下文菜单 的本地化字符串。
        /// </summary>
        public static string RightClickToOpenContextMenu {
            get {
                return ResourceManager.GetString("RightClickToOpenContextMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 生物群系 的本地化字符串。
        /// </summary>
        public static string RuleBiome {
            get {
                return ResourceManager.GetString("RuleBiome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 情感动作 的本地化字符串。
        /// </summary>
        public static string RuleEmote {
            get {
                return ResourceManager.GetString("RuleEmote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 套装 的本地化字符串。
        /// </summary>
        public static string RuleGearset {
            get {
                return ResourceManager.GetString("RuleGearset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 住宅 的本地化字符串。
        /// </summary>
        public static string RuleHouse {
            get {
                return ResourceManager.GetString("RuleHouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 职业 的本地化字符串。
        /// </summary>
        public static string RuleJob {
            get {
                return ResourceManager.GetString("RuleJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 预设 的本地化字符串。
        /// </summary>
        public static string RulePreset {
            get {
                return ResourceManager.GetString("RulePreset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 状态 的本地化字符串。
        /// </summary>
        public static string RuleState {
            get {
                return ResourceManager.GetString("RuleState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 时间 的本地化字符串。
        /// </summary>
        public static string RuleTime {
            get {
                return ResourceManager.GetString("RuleTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 天气 的本地化字符串。
        /// </summary>
        public static string RuleWeather {
            get {
                return ResourceManager.GetString("RuleWeather", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 服务器 的本地化字符串。
        /// </summary>
        public static string RuleWorld {
            get {
                return ResourceManager.GetString("RuleWorld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 区域 的本地化字符串。
        /// </summary>
        public static string RuleZone {
            get {
                return ResourceManager.GetString("RuleZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 区域类型 的本地化字符串。
        /// </summary>
        public static string RuleZoneGroup {
            get {
                return ResourceManager.GetString("RuleZoneGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 按角色名称搜索... 的本地化字符串。
        /// </summary>
        public static string SearchCharacterName {
            get {
                return ResourceManager.GetString("SearchCharacterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 按名称搜索配置文件... 的本地化字符串。
        /// </summary>
        public static string SearchProfileName {
            get {
                return ResourceManager.GetString("SearchProfileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择允许生效的区域 的本地化字符串。
        /// </summary>
        public static string SelectAllowListZones {
            get {
                return ResourceManager.GetString("SelectAllowListZones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择禁止生效的区域 的本地化字符串。
        /// </summary>
        public static string SelectDenyListZones {
            get {
                return ResourceManager.GetString("SelectDenyListZones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择此配置文件进行编辑 的本地化字符串。
        /// </summary>
        public static string SelectThisProfileForEditing {
            get {
                return ResourceManager.GetString("SelectThisProfileForEditing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 在动态规则的预设下拉菜单中显示 的本地化字符串。
        /// </summary>
        public static string ShowInRulesSection {
            get {
                return ResourceManager.GetString("ShowInRulesSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 拆分职业类型和职业 的本地化字符串。
        /// </summary>
        public static string SplitBaseClassesAndJobs {
            get {
                return ResourceManager.GetString("SplitBaseClassesAndJobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 角色管理 的本地化字符串。
        /// </summary>
        public static string TabCharacters {
            get {
                return ResourceManager.GetString("TabCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 动态规则 的本地化字符串。
        /// </summary>
        public static string TabDynamicRules {
            get {
                return ResourceManager.GetString("TabDynamicRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 全局预设 的本地化字符串。
        /// </summary>
        public static string TabGlobalPresets {
            get {
                return ResourceManager.GetString("TabGlobalPresets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 住宅登记 的本地化字符串。
        /// </summary>
        public static string TabHouseRegistration {
            get {
                return ResourceManager.GetString("TabHouseRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 独立预设 的本地化字符串。
        /// </summary>
        public static string TabPresets {
            get {
                return ResourceManager.GetString("TabPresets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 配置文件 的本地化字符串。
        /// </summary>
        public static string TabProfiles {
            get {
                return ResourceManager.GetString("TabProfiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 插件设置 的本地化字符串。
        /// </summary>
        public static string TabSettings {
            get {
                return ResourceManager.GetString("TabSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 教程 的本地化字符串。
        /// </summary>
        public static string TabTutorial {
            get {
                return ResourceManager.GetString("TabTutorial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 欢迎使用DynamicBridge插件！
        ///此插件允许您根据各种规则动态地更改Glamourer、Customize+和Honorific的自定义设计。您可以使用此插件只进行简单的操作，例如手动切换外观，也可以创建非常复杂和精确的规则合集。
        ///---
        ///如果您以前使用过旧版本的插件，您的配置已被转换为更易于使用的配置文件系统。为了防止出现问题，旧配置文件也已进行了备份。
        ///现在可以创建配置文件并将其分配给角色，而不是强制给每个角色执行对应的配置文件。这样您就可以为多个角色使用同一个配置文件，也可以轻松地修改用于您的角色的配置文件。
        ///---
        ///+快速了解
        ///我将按您开始使用此插件所需的最少步骤来描述。
        ///首先，假设您以前从未创建过配置文件，在游戏中登录到您的角色，切换到“动态规则”或“独立预设”选项卡，然后单击“+”按钮：
        ///image=1
        ///这将为您创建新的配置文件，并将其与当前角色关联。现在，您可以根据自己的喜好创建规则和预设。
        ///+规则和预设
        ///DynamicBridge会一直跟踪您的角色状态，并从上到下依次检查动态规则。一旦找到正确的规则，所选规则中的相应设置将应用到您的角色，其他规则将停止处理。当前 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string Tutorial {
            get {
                return ResourceManager.GetString("Tutorial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 将该角色从黑名单中移出 的本地化字符串。
        /// </summary>
        public static string UnblacklistThisCharacter {
            get {
                return ResourceManager.GetString("UnblacklistThisCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未知角色 $ 的本地化字符串。
        /// </summary>
        public static string UnknownCharacter {
            get {
                return ResourceManager.GetString("UnknownCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不支持的版本 的本地化字符串。
        /// </summary>
        public static string UnsupportedVersion {
            get {
                return ResourceManager.GetString("UnsupportedVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用于 的本地化字符串。
        /// </summary>
        public static string UsedByColumn {
            get {
                return ResourceManager.GetString("UsedByColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在使用动态规则。 的本地化字符串。
        /// </summary>
        public static string UsingDynamicRulesNow {
            get {
                return ResourceManager.GetString("UsingDynamicRulesNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 将在以下选项中随机选择：\n 的本地化字符串。
        /// </summary>
        public static string WillBeRandomlySelectedBetween {
            get {
                return ResourceManager.GetString("WillBeRandomlySelectedBetween", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您正在编辑配置文件 &quot;$&quot;.  的本地化字符串。
        /// </summary>
        public static string YouAreEditingProfile {
            get {
                return ResourceManager.GetString("YouAreEditingProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您正在编辑配置文件 &quot;$1&quot; 它被用于 &quot;$2&quot;. 的本地化字符串。
        /// </summary>
        public static string YouAreEditingProfile1WhichIsUsedBy2 {
            get {
                return ResourceManager.GetString("YouAreEditingProfile1WhichIsUsedBy2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您尚未登录。请选择要编辑的配置文件。 的本地化字符串。
        /// </summary>
        public static string YouAreNotLoggedInPleaseSelectProfileToEdit {
            get {
                return ResourceManager.GetString("YouAreNotLoggedInPleaseSelectProfileToEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您当前的角色已列入黑名单 的本地化字符串。
        /// </summary>
        public static string YourCurrentCharacterIsBlacklisted {
            get {
                return ResourceManager.GetString("YourCurrentCharacterIsBlacklisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 区域组 的本地化字符串。
        /// </summary>
        public static string ZoneGroup {
            get {
                return ResourceManager.GetString("ZoneGroup", resourceCulture);
            }
        }
    }
}
